//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QR_Tracker.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QR_Tracker.Properties.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   아이디 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AdminId {
            get {
                return ResourceManager.GetString("AdminId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   관리자 모드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AdminModeButton {
            get {
                return ResourceManager.GetString("AdminModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   관리자 모드 종료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AdminModeExitButton {
            get {
                return ResourceManager.GetString("AdminModeExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비밀번호 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AdminPw {
            get {
                return ResourceManager.GetString("AdminPw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시간과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChartXTime {
            get {
                return ResourceManager.GetString("ChartXTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   인원수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChartYEmployeeNum {
            get {
                return ResourceManager.GetString("ChartYEmployeeNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   생성 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   일일 리포트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DailyReportButton {
            get {
                return ResourceManager.GetString("DailyReportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사번 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EmployeeNumber {
            get {
                return ResourceManager.GetString("EmployeeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   월간 리포트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MonthReportButton {
            get {
                return ResourceManager.GetString("MonthReportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름 : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이름과 사번을 입력하여 QR 코드를 생성하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string QrCreateGuide {
            get {
                return ResourceManager.GetString("QrCreateGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   QR 생성과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string QrCreateMenu {
            get {
                return ResourceManager.GetString("QrCreateMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   QR 코드를 화면에 인식해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string QrDetectGuide {
            get {
                return ResourceManager.GetString("QrDetectGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   QR 인식과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string QrDetectMenu {
            get {
                return ResourceManager.GetString("QrDetectMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   QR 출퇴근 시스템과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string QrTrackerTitle {
            get {
                return ResourceManager.GetString("QrTrackerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   리포트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReportMenu {
            get {
                return ResourceManager.GetString("ReportMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   주간 리포트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WeekReportButton {
            get {
                return ResourceManager.GetString("WeekReportButton", resourceCulture);
            }
        }
    }
}
